<center> 
    <h1> Toronto Crime </h1>
<h3> Sprint 1</h3>
<h3> Data Cleaning</h3>
    </center>

##### Author: Arsalan Arif Radhu
##### Date: 11 October 2023

### Table of Contents:
- [Introduction](#intro) <br />
- [Basic Cleaning](#part1) <br />

### Introduction <a id="intro" />

This notebook aims to merge multiple datasets into one for cleaning and analysis.

Importing all the required libraries.

In [1]:
import numpy as np  #importing numpy library
import pandas as pd #importing pandas library
import matplotlib.pyplot as plt #importing matplotlib library
import seaborn as sns #importing seaborn library 
import statsmodels.api as sm #importing statsmodel library 
from scipy import stats #importing scientific py library 
import datetime

### Basic Cleaning <a id="part1" />

We will first import the new dataset and do some basic EDA to get a grasp of how it is after the processing.

Importing our data and reading through it.

In [2]:
#Reading the csv file
assualt_df = pd.read_csv('../Data/Assualt.csv',low_memory=False, index_col=0)
autoTheft_df = pd.read_csv('../Data/Auto Theft.csv',low_memory=False, index_col=0)
bicycleTheft_df = pd.read_csv('../Data/Bicycle Theft.csv',low_memory=False, index_col=0)
homicide_df = pd.read_csv('../Data/Homicide.csv',low_memory=False, index_col=0)
motorTheft_df = pd.read_csv('../Data/Motor Theft.csv',low_memory=False, index_col=0)
robbery_df = pd.read_csv('../Data/Robbery.csv',low_memory=False, index_col=0)
shootings_df = pd.read_csv('../Data/Shootings.csv',low_memory=False, index_col=0)
theftOver_df = pd.read_csv('../Data/Theft Over.csv',low_memory=False, index_col=0)

final=[assualt_df,autoTheft_df,bicycleTheft_df,homicide_df,motorTheft_df,robbery_df,shootings_df,theftOver_df] 

"""
Go through all th data files, and fix the columns expecially dates.regfgf
fgsdf
wwww
subin

"""
#HEllo World.;

final_df=pd.concat(final)

In [5]:
final_df.sample(100)

,EVENT_UNIQUE_ID,REPORT_DATE_FIXED,OCC_DATE_FIXED,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,...,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,LONG_WGS84,LAT_WGS84,PRIMARY_OFFENCE,STATUS,HOMICIDE_TYPE,DEATH,INJURIES
OBJECTID,,,,,,,,,,,,,,,,,,,,,
23629,GO-20209017820,2020-07-17,2020-07-14,2020.0,July,17.0,199.0,Friday,18.0,2020.0,...,NaN,151,Yonge-Doris,-79.408620,43.764959,THEFT UNDER - BICYCLE,STOLEN,NaN,NaN,NaN
31311,GO-2021664499,2021-04-11,2021-04-11,2021.0,April,11.0,101.0,Sunday,13.0,2021.0,...,Auto Theft,78,Kensington-Chinatown,-79.403104,43.653600,NaN,NaN,NaN,NaN,NaN
68221,GO-20211422687,2021-07-28,2021-07-27,2021.0,July,28.0,209.0,Wednesday,19.0,2021.0,...,NonMCI,25,Glenfield-Jane Heights,-79.522923,43.751382,NaN,NaN,NaN,NaN,NaN
9948,GO-20169013344,2016-11-13,2016-11-10,2016.0,November,13.0,318.0,Sunday,13.0,2016.0,...,NaN,37,Willowdale West,-79.417292,43.778393,THEFT UNDER - BICYCLE,STOLEN,NaN,NaN,NaN
122592,GO-20201176511,2020-06-26,2020-06-24,2020.0,June,26.0,178.0,Friday,12.0,2020.0,...,Assault,100,Yonge-Eglinton,-79.406436,43.699495,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45677,GO-2019526134,2019-03-23,2019-03-23,2019.0,March,23.0,82.0,Saturday,13.0,2019.0,...,NonMCI,171,Junction-Wallace Emerson,-79.449084,43.669934,NaN,NaN,NaN,NaN,NaN
27990,GO-2022183279,2022-01-28,2022-01-28,2022.0,January,28.0,28.0,Friday,13.0,2022.0,...,Robbery,119,Wexford/Maryvale,-79.302167,43.765574,NaN,NaN,NaN,NaN,NaN
105801,GO-20191503112,2019-08-09,2019-08-09,2019.0,August,9.0,221.0,Friday,1.0,2019.0,...,Assault,84,Little Portugal,-79.425821,43.649477,NaN,NaN,NaN,NaN,NaN
10198,GO-2015102843,2015-01-18,2015-01-18,2015.0,January,18.0,18.0,Sunday,13.0,2015.0,...,NonMCI,5,Elms-Old Rexdale,-79.548949,43.718097,NaN,NaN,NaN,NaN,NaN
172402,GO-20222470015,2022-12-18,2022-12-18,2022.0,December,18.0,352.0,Sunday,15.0,2022.0,...,Assault,43,Victoria Village,-79.314237,43.741492,NaN,NaN,NaN,NaN,NaN

The data looks to have concatenated well and the number of columns have risen to <b>43!</b> So, I will be dropping some columns which contained either useless data, redundant data or data which is not necessary for my analysis.

In [3]:
# Doesn't make sense
final_df.drop('F_num_removed', axis=1, inplace=True)
final_df.drop('OCC_TIME_RANGE', axis=1, inplace=True)

# Old redundant data 
final_df.drop('NEIGHBOURHOOD_140', axis=1, inplace=True)
final_df.drop('HOOD_140', axis=1, inplace=True)
final_df.drop('REPORT_DATE', axis=1, inplace=True)
final_df.drop('OCC_DATE', axis=1, inplace=True)

# Resetting index since it got mixed up while concatanating 
final_df.reset_index(drop=True)

# Are not going to be used in my analysis
final_df.drop('BIKE_MAKE', axis=1, inplace=True)
final_df.drop('BIKE_MODEL', axis=1, inplace=True)
final_df.drop('BIKE_TYPE', axis=1, inplace=True)
final_df.drop('BIKE_SPEED', axis=1, inplace=True)
final_df.drop('BIKE_COLOUR', axis=1, inplace=True)
final_df.drop('BIKE_COST', axis=1, inplace=True)

In [6]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 381419 entries, 1 to 10745
Data columns (total 31 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   EVENT_UNIQUE_ID    381419 non-null  object
 1   REPORT_DATE_FIXED  374390 non-null  object
 2   OCC_DATE_FIXED     380097 non-null  object
 3   REPORT_YEAR        374390 non-null  float64
 4   REPORT_MONTH       374390 non-null  object
 5   REPORT_DAY         374390 non-null  float64
 6   REPORT_DOY         374390 non-null  float64
 7   REPORT_DOW         374390 non-null  object
 8   REPORT_HOUR        374390 non-null  float64
 9   OCC_YEAR           381298 non-null  float64
 10  OCC_MONTH          381298 non-null  object
 11  OCC_DAY            381298 non-null  float64
 12  OCC_DOY            381298 non-null  float64
 13  OCC_DOW            381298 non-null  object
 14  OCC_HOUR           380097 non-null  float64
 15  DIVISION           381419 non-null  object
 16  LOCATION_TYPE      374390 non-null  object
 17  PREMISES_TYPE      374390 non-null  object
 18  UCR_CODE           342420 non-null  float64
 19  UCR_EXT            342420 non-null  float64
 20  OFFENCE            342420 non-null  object
 21  MCI_CATEGORY       342420 non-null  object
 22  HOOD_158           381419 non-null  object
 23  NEIGHBOURHOOD_158  381419 non-null  object
 24  LONG_WGS84         381419 non-null  float64
 25  LAT_WGS84          381419 non-null  float64
 26  PRIMARY_OFFENCE    31970 non-null   object
 27  STATUS             31970 non-null   object
 28  HOMICIDE_TYPE      1322 non-null    object
 29  DEATH              5707 non-null    float64
 30  INJURIES           5707 non-null    float64
dtypes: float64(14), object(17)
memory usage: 93.1+ MB

As we can see, after dropping all the unnecessary columns we are left with <b>31</b> columns. We can also observe that there seems to be a lot of `NULL` values. So, let's check for them!

In [7]:
final_df.isna().sum()

EVENT_UNIQUE_ID           0
REPORT_DATE_FIXED      7029
OCC_DATE_FIXED         1322
REPORT_YEAR            7029
REPORT_MONTH           7029
REPORT_DAY             7029
REPORT_DOY             7029
REPORT_DOW             7029
REPORT_HOUR            7029
OCC_YEAR                121
OCC_MONTH               121
OCC_DAY                 121
OCC_DOY                 121
OCC_DOW                 121
OCC_HOUR               1322
DIVISION                  0
LOCATION_TYPE          7029
PREMISES_TYPE          7029
UCR_CODE              38999
UCR_EXT               38999
OFFENCE               38999
MCI_CATEGORY          38999
HOOD_158                  0
NEIGHBOURHOOD_158         0
LONG_WGS84                0
LAT_WGS84                 0
PRIMARY_OFFENCE      349449
STATUS               349449
HOMICIDE_TYPE        380097
DEATH                375712
INJURIES             375712
dtype: int64

As we can see there are a lot of `NULL` values. After doing some research I realized the `DEATH` and `INJURIES` columns were specific for `Shooting` dataset, and hence the huge amounts of `NULL` values. So, to fix that I will be filling the `NULL` values in these two columns with `0` as this will indicate that no-one was injured or killed in any other types of crimes. The `HOMICIDE_TYPE` column is also specific to the `Homicide` dataset hence I will be filling the `NULL` values with "N/A". Similarly, `STATUS` and `PRIMARY_OFFENCE` is specific to the `Bike_Theft` data set, so I will be filling the `NULL` values wiht "N/A". The reason I am not dropping these columns is that even though they are specific to one type of crime, they provide very valuable insight into that crime, so for now I don't have any strong reasons to drop them.
`OFFENCE`,`UCR_EXIT`and `UCR_CODE` columns have exact same number of `NULL`, which implies that all of them might come from the same data set and after further investigation that was the case. They were `NULL` due to them not being present in the `Bike Theft` data set, since they're not a required category for them we can fill these with `N/A` as well.

In [8]:
# Filling the NULL values
final_df["DEATH"] = final_df["DEATH"].fillna(0)
final_df["INJURIES"] = final_df["INJURIES"].fillna(0)
final_df["HOMICIDE_TYPE"] = final_df["HOMICIDE_TYPE"].fillna("N/A")
final_df["STATUS"] = final_df["STATUS"].fillna("N/A")
final_df["PRIMARY_OFFENCE"] = final_df["PRIMARY_OFFENCE"].fillna("N/A")
final_df["MCI_CATEGORY"] = final_df["MCI_CATEGORY"].fillna("NonMCI")
final_df["OFFENCE"] = final_df["OFFENCE"].fillna("N/A")
final_df["UCR_EXT"] = final_df["UCR_EXT"].fillna("N/A")
final_df["UCR_CODE"] = final_df["UCR_CODE"].fillna("N/A")

In [9]:
final_df.isna().sum()

EVENT_UNIQUE_ID         0
REPORT_DATE_FIXED    7029
OCC_DATE_FIXED       1322
REPORT_YEAR          7029
REPORT_MONTH         7029
REPORT_DAY           7029
REPORT_DOY           7029
REPORT_DOW           7029
REPORT_HOUR          7029
OCC_YEAR              121
OCC_MONTH             121
OCC_DAY               121
OCC_DOY               121
OCC_DOW               121
OCC_HOUR             1322
DIVISION                0
LOCATION_TYPE        7029
PREMISES_TYPE        7029
UCR_CODE                0
UCR_EXT                 0
OFFENCE                 0
MCI_CATEGORY            0
HOOD_158                0
NEIGHBOURHOOD_158       0
LONG_WGS84              0
LAT_WGS84               0
PRIMARY_OFFENCE         0
STATUS                  0
HOMICIDE_TYPE           0
DEATH                   0
INJURIES                0
dtype: int64

After filling majority of `NULL` values we are still left with some, I could not really find a good way of substituiting them so I will be dropping them. This should not affect the analysis much because of the huge number of data I have.

In [10]:
final_df= final_df.dropna(axis=0)

Now checking for duplicates in the data.

In [11]:
final_df.duplicated().sum()

29430

As we can see we have around `~30,000` duplicates! Let's check whether they are actually duplicates or not.

In [12]:
final_df.loc[final_df.duplicated(), :].sort_values("EVENT_UNIQUE_ID")

,EVENT_UNIQUE_ID,REPORT_DATE_FIXED,OCC_DATE_FIXED,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,...,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,LONG_WGS84,LAT_WGS84,PRIMARY_OFFENCE,STATUS,HOMICIDE_TYPE,DEATH,INJURIES
OBJECTID,,,,,,,,,,,,,,,,,,,,,
62,GO-20141259762,2014-01-01,2013-12-31,2014.0,January,1.0,1.0,Wednesday,2.0,2013.0,...,Assault,164,Wellington Place,-79.390935,43.649445,N/A,N/A,N/A,0.0,0.0
67,GO-20141259834,2014-01-01,2014-01-01,2014.0,January,1.0,1.0,Wednesday,0.0,2014.0,...,Assault,55,Thorncliffe Park,-79.345795,43.703684,N/A,N/A,N/A,0.0,0.0
63,GO-20141260033,2014-01-01,2013-12-31,2014.0,January,1.0,1.0,Wednesday,2.0,2013.0,...,Assault,144,Morningside Heights,-79.180578,43.806750,N/A,N/A,N/A,0.0,0.0
42,GO-20141260264,2014-01-01,2014-01-01,2014.0,January,1.0,1.0,Wednesday,1.0,2014.0,...,Assault,143,West Rouge,-79.132919,43.780412,N/A,N/A,N/A,0.0,0.0
66,GO-20141260618,2014-01-01,2014-01-01,2014.0,January,1.0,1.0,Wednesday,5.0,2014.0,...,Assault,81,Trinity-Bellwoods,-79.416594,43.654753,N/A,N/A,N/A,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40006,GO-2022995203,2022-05-27,2022-05-22,2022.0,May,27.0,147.0,Friday,7.0,2022.0,...,Auto Theft,23,Pelmo Park-Humberlea,-79.537287,43.717017,N/A,N/A,N/A,0.0,0.0
40001,GO-2022995776,2022-05-27,2022-05-26,2022.0,May,27.0,147.0,Friday,8.0,2022.0,...,Auto Theft,108,Briar Hill-Belgravia,-79.449333,43.695892,N/A,N/A,N/A,0.0,0.0
9807,GO-2022995987,2022-05-27,2022-05-24,2022.0,May,27.0,147.0,Friday,15.0,2022.0,...,Theft Over,159,Etobicoke City Centre,-79.527286,43.634209,N/A,N/A,N/A,0.0,0.0
40003,GO-2022997755,2022-05-27,2022-05-26,2022.0,May,27.0,147.0,Friday,13.0,2022.0,...,Auto Theft,108,Briar Hill-Belgravia,-79.449333,43.695892,N/A,N/A,N/A,0.0,0.0
159668,GO-2022999907,2022-05-27,2022-05-27,2022.0,May,27.0,147.0,Friday,19.0,2022.0,...,Assault,70,South Riverdale,-79.328487,43.659320,N/A,N/A,N/A,0.0,0.0

There seems to be some real duplicates! So we can drop the duplicates!

In [13]:
final_df= final_df.drop_duplicates()

After dropping, we have no more duplicates left as confirmed below!

In [14]:
final_df.duplicated().sum()

0

Just a final check before we can export this final 'clean' copy of the data set.

In [16]:
final_df.sample(10)

,EVENT_UNIQUE_ID,REPORT_DATE_FIXED,OCC_DATE_FIXED,REPORT_YEAR,REPORT_MONTH,REPORT_DAY,REPORT_DOY,REPORT_DOW,REPORT_HOUR,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOY,OCC_DOW,OCC_HOUR,DIVISION,LOCATION_TYPE,PREMISES_TYPE,UCR_CODE,UCR_EXT,OFFENCE,MCI_CATEGORY,HOOD_158,NEIGHBOURHOOD_158,LONG_WGS84,LAT_WGS84,PRIMARY_OFFENCE,STATUS,HOMICIDE_TYPE,DEATH,INJURIES
OBJECTID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
20152,GO-2016490290,2016-03-22,2016-03-21,2016.0,March,22.0,82.0,Tuesday,9.0,2016.0,March,21.0,81.0,Monday,20.0,D53,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,2142.0,200.0,Theft From Motor Vehicle Under,NonMCI,97,Yonge-St.Clair,-79.401369,43.696362,N/A,N/A,N/A,0.0,0.0
8331,GO-20142438621,2014-07-05,2014-07-05,2014.0,July,5.0,186.0,Saturday,22.0,2014.0,July,5.0,186.0,Saturday,22.0,D55,"Single Home, House (Attach Garage, Cottage, Mo...",House,1430.0,100.0,Assault,Assault,70,South Riverdale,-79.337516,43.671177,N/A,N/A,N/A,0.0,0.0
6738,GO-20169002904,2016-03-30,2016-03-01,2016.0,March,30.0,90.0,Wednesday,14.0,2016.0,March,1.0,61.0,Tuesday,1.0,D52,Other Commercial / Corporate Places (For Profi...,Commercial,N/A,N/A,N/A,NonMCI,164,Wellington Place,-79.390583,43.646924,THEFT UNDER - BICYCLE,STOLEN,N/A,0.0,0.0
58765,GO-2017642468,2017-04-12,2017-04-12,2017.0,April,12.0,102.0,Wednesday,1.0,2017.0,April,12.0,102.0,Wednesday,1.0,D14,"Apartment (Rooming House, Condo)",Apartment,1430.0,100.0,Assault,Assault,165,Harbourfront-CityPlace,-79.396021,43.640894,N/A,N/A,N/A,0.0,0.0
90090,GO-20182047486,2018-11-06,2018-11-06,2018.0,November,6.0,310.0,Tuesday,12.0,2018.0,November,6.0,310.0,Tuesday,12.0,D41,"Parking Lots (Apt., Commercial Or Non-Commercial)",Outside,1430.0,100.0,Assault,Assault,126,Dorset Park,-79.283247,43.771727,N/A,N/A,N/A,0.0,0.0
41272,GO-20221378585,2022-07-19,2022-07-18,2022.0,July,19.0,200.0,Tuesday,10.0,2022.0,July,18.0,199.0,Monday,22.0,D53,"Single Home, House (Attach Garage, Cottage, Mo...",House,2135.0,210.0,Theft Of Motor Vehicle,Auto Theft,103,Lawrence Park South,-79.394354,43.723700,N/A,N/A,N/A,0.0,0.0
94356,GO-2019176295,2019-01-28,2019-01-28,2019.0,January,28.0,28.0,Monday,18.0,2019.0,January,28.0,28.0,Monday,18.0,D51,"Apartment (Rooming House, Condo)",Apartment,1457.0,100.0,Pointing A Firearm,Assault,74,North St.James Town,-79.372205,43.667629,N/A,N/A,N/A,0.0,0.0
27844,GO-20211584167,2021-08-20,2021-08-20,2021.0,August,20.0,232.0,Friday,15.0,2021.0,August,20.0,232.0,Friday,6.0,D14,Other Commercial / Corporate Places (For Profi...,Commercial,N/A,N/A,N/A,NonMCI,172,Dovercourt Village,-79.436994,43.668837,B&E,STOLEN,N/A,0.0,0.0
27868,GO-20201679905,2020-09-05,2020-09-05,2020.0,September,5.0,249.0,Saturday,13.0,2020.0,September,5.0,249.0,Saturday,13.0,D55,"Parking Lots (Apt., Commercial Or Non-Commercial)",Outside,2135.0,210.0,Theft Of Motor Vehicle,Auto Theft,70,South Riverdale,-79.328212,43.658878,N/A,N/A,N/A,0.0,0.0
39136,GO-2016518636,2016-03-27,2016-03-27,2016.0,March,27.0,87.0,Sunday,2.0,2016.0,March,27.0,87.0,Sunday,2.0,D23,"Streets, Roads, Highways (Bicycle Path, Privat...",Outside,1430.0,100.0,Assault,Assault,8,Humber Heights-Westmount,-79.512835,43.686240,N/A,N/A,N/A,0.0,0.0

It looks good! I think we can export it into a new file, and we can start our basic EDA.

In [17]:
final_df.to_csv('FinalData.csv')